module.exports = {
  sections: [
    { title: 'System', lines: ['OS', 'CPU', 'Memory', 'Container', 'Shell'] },
    { title: 'Binaries', lines: ['Node', 'Yarn', 'npm', 'Watchman'] },
    { title: 'Utilities', lines: ['CMake', 'Make', 'GCC', 'Git'] },
    { title: 'Servers', lines: ['Apache', 'Nginx'] },
    { title: 'Virtualization', lines: ['Docker', 'Parallels', 'VirtualBox', 'VMware Fusion'] },
    { title: 'SDKs', lines: ['iOS SDK', 'Android SDK'] },
    {
      title: 'IDEs',
      lines: [
        'Android Studio',
        'Atom',
        'Emacs',
        'IntelliJ',
        'NVim',
        'Nano',
        'PhpStorm',
        'Sublime Text',
        'VSCode',
        'Vim',
        'WebStorm',
        'Xcode',
      ],
    },
    {
      title: 'Languages',
      lines: ['Bash', 'Go', 'Elixir', 'Java', 'Perl', 'PHP', 'Python', 'Ruby', 'Rust', 'Scala'],
    },
    { title: 'Databases', lines: ['MongoDB', 'MySQL', 'PostgreSQL', 'SQLite'] },
    {
      title: 'Browsers',
      lines: [
        'Chrome',
        'Chrome Canary',
        'Edge',
        'Firefox',
        'Firefox Developer Edition',
        'Firefox Nightly',
        'Internet Explorer',
        'Safari',
        'Safari Technology Preview',
      ],
    },
  ],
};
